# PowerShell script to create all remaining template files
$templatesDir = "templates"
$baseTemplate = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}} | Enterprise Room Business Hub</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: Arial, sans-serif;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            background: #f5f5f5;
        }
        .template-container {
            background: white;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 2px solid #1e40af;
        }
        .header h1 {
            color: #1e40af;
            margin-bottom: 10px;
        }
        .content {
            line-height: 1.8;
            color: #333;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            color: #1e40af;
            margin-bottom: 15px;
            padding-bottom: 5px;
            border-bottom: 1px solid #ddd;
        }
        .field {
            margin-bottom: 15px;
        }
        .field label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }
        .field input, .field textarea {
            width: 100%;
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th {
            background: #1e40af;
            color: white;
            padding: 10px;
            text-align: left;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        .enterprise-footer {
            margin-top: 40px;
            padding: 15px;
            background: #e6f2ff;
            border-left: 4px solid #1e40af;
            font-size: 0.85rem;
            color: #666;
        }
        .enterprise-footer strong {
            color: #1e40af;
        }
        @media print {
            body { background: white; padding: 0; }
            .enterprise-footer { display: none; }
        }
    </style>
</head>
<body>
    <div class="template-container">
        <div class="header">
            <h1>{{TITLE}}</h1>
            <p>{{DESCRIPTION}}</p>
        </div>
        <div class="content">
            {{CONTENT}}
        </div>
        <div class="enterprise-footer">
            <strong>Template provided by Enterprise Room Business Hub</strong><br>
            This document template is free to use. You may remove this footer if desired.
        </div>
    </div>
</body>
</html>
"@

$templates = @(
    @{id='business-plan'; title='Business Plan Template'; desc='Complete business plan document'; content='<div class="section"><h2>Executive Summary</h2><div class="field"><label>Company Name:</label><input type="text" placeholder="Enter company name"></div><div class="field"><label>Business Description:</label><textarea rows="4" placeholder="Describe your business"></textarea></div></div><div class="section"><h2>Market Analysis</h2><div class="field"><label>Target Market:</label><textarea rows="3" placeholder="Describe your target market"></textarea></div><div class="field"><label>Competitive Analysis:</label><textarea rows="3" placeholder="Analyze your competitors"></textarea></div></div><div class="section"><h2>Financial Projections</h2><div class="field"><label>Revenue Projections:</label><input type="text" placeholder="Enter revenue projections"></div><div class="field"><label>Expense Projections:</label><input type="text" placeholder="Enter expense projections"></div></div>'}
    @{id='swot-analysis'; title='SWOT Analysis Template'; desc='Business strengths, weaknesses, opportunities, threats'; content='<div class="section"><h2>Strengths</h2><textarea rows="5" placeholder="List your business strengths"></textarea></div><div class="section"><h2>Weaknesses</h2><textarea rows="5" placeholder="List your business weaknesses"></textarea></div><div class="section"><h2>Opportunities</h2><textarea rows="5" placeholder="List opportunities in the market"></textarea></div><div class="section"><h2>Threats</h2><textarea rows="5" placeholder="List potential threats"></textarea></div>'}
    @{id='business-model-canvas'; title='Business Model Canvas'; desc='One-page business model framework'; content='<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:15px;"><div class="section"><h2>Key Partners</h2><textarea rows="4"></textarea></div><div class="section"><h2>Key Activities</h2><textarea rows="4"></textarea></div><div class="section"><h2>Key Resources</h2><textarea rows="4"></textarea></div><div class="section"><h2>Value Propositions</h2><textarea rows="4"></textarea></div><div class="section"><h2>Customer Relationships</h2><textarea rows="4"></textarea></div><div class="section"><h2>Channels</h2><textarea rows="4"></textarea></div><div class="section"><h2>Customer Segments</h2><textarea rows="4"></textarea></div><div class="section"><h2>Cost Structure</h2><textarea rows="4"></textarea></div><div class="section"><h2>Revenue Streams</h2><textarea rows="4"></textarea></div></div>'}
    @{id='marketing-plan'; title='Marketing Plan Template'; desc='Comprehensive marketing strategy'; content='<div class="section"><h2>Marketing Objectives</h2><textarea rows="4" placeholder="Define your marketing objectives"></textarea></div><div class="section"><h2>Target Audience</h2><textarea rows="3" placeholder="Describe your target audience"></textarea></div><div class="section"><h2>Marketing Channels</h2><textarea rows="4" placeholder="List marketing channels"></textarea></div><div class="section"><h2>Budget</h2><div class="field"><label>Marketing Budget (₦):</label><input type="text" placeholder="Enter budget amount"></div></div><div class="section"><h2>Key Performance Indicators</h2><textarea rows="3" placeholder="Define KPIs"></textarea></div>'}
    @{id='quotation'; title='Quotation Template'; desc='Professional price quotation'; content='<div class="section"><h2>Quotation Details</h2><div class="field"><label>Quotation #:</label><input type="text" placeholder="QUO-001"></div><div class="field"><label>Date:</label><input type="date"></div><div class="field"><label>Valid Until:</label><input type="date"></div></div><div class="section"><h2>Client Information</h2><div class="field"><label>Client Name:</label><input type="text"></div><div class="field"><label>Client Address:</label><textarea rows="2"></textarea></div></div><div class="section"><h2>Items/Services</h2><table><thead><tr><th>Description</th><th>Qty</th><th>Unit Price (₦)</th><th>Total (₦)</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Terms & Conditions</h2><textarea rows="4" placeholder="Payment terms and conditions"></textarea></div>'}
    @{id='purchase-order'; title='Purchase Order Template'; desc='Standardized purchase order form'; content='<div class="section"><h2>Purchase Order Details</h2><div class="field"><label>PO Number:</label><input type="text" placeholder="PO-001"></div><div class="field"><label>Date:</label><input type="date"></div><div class="field"><label>Delivery Date:</label><input type="date"></div></div><div class="section"><h2>Vendor Information</h2><div class="field"><label>Vendor Name:</label><input type="text"></div><div class="field"><label>Vendor Address:</label><textarea rows="2"></textarea></div></div><div class="section"><h2>Items Ordered</h2><table><thead><tr><th>Item</th><th>Qty</th><th>Unit Price (₦)</th><th>Total (₦)</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div>'}
    @{id='expense-report'; title='Expense Report Template'; desc='Employee expense tracking form'; content='<div class="section"><h2>Employee Information</h2><div class="field"><label>Employee Name:</label><input type="text"></div><div class="field"><label>Department:</label><input type="text"></div><div class="field"><label>Report Period:</label><input type="text" placeholder="Month/Year"></div></div><div class="section"><h2>Expenses</h2><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount (₦)</th></tr></thead><tbody><tr><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Total Expenses</h2><div class="field"><label>Total Amount (₦):</label><input type="text" placeholder="0.00"></div></div>'}
    @{id='budget'; title='Budget Template'; desc='Monthly and annual budget planning'; content='<div class="section"><h2>Budget Period</h2><div class="field"><label>Period:</label><input type="text" placeholder="Month/Year"></div></div><div class="section"><h2>Income</h2><div class="field"><label>Projected Income (₦):</label><input type="text"></div></div><div class="section"><h2>Expenses</h2><table><thead><tr><th>Category</th><th>Budgeted (₦)</th><th>Actual (₦)</th><th>Variance (₦)</th></tr></thead><tbody><tr><td>Salaries</td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Marketing</td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Operations</td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div>'}
    @{id='cash-flow-statement'; title='Cash Flow Statement Template'; desc='Track monthly cash inflows and outflows'; content='<div class="section"><h2>Cash Flow Statement</h2><div class="field"><label>Period:</label><input type="text" placeholder="Month/Year"></div></div><div class="section"><h2>Cash Inflows</h2><table><thead><tr><th>Source</th><th>Amount (₦)</th></tr></thead><tbody><tr><td>Sales Revenue</td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Other Income</td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Cash Outflows</h2><table><thead><tr><th>Category</th><th>Amount (₦)</th></tr></thead><tbody><tr><td>Operating Expenses</td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Capital Expenditures</td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Net Cash Flow</h2><div class="field"><label>Net Cash Flow (₦):</label><input type="text" placeholder="0.00"></div></div>'}
    @{id='profit-loss-statement'; title='Profit & Loss Statement Template'; desc='Monthly and quarterly P&L statement'; content='<div class="section"><h2>Profit & Loss Statement</h2><div class="field"><label>Period:</label><input type="text" placeholder="Month/Quarter/Year"></div></div><div class="section"><h2>Revenue</h2><div class="field"><label>Total Revenue (₦):</label><input type="text"></div></div><div class="section"><h2>Cost of Goods Sold</h2><div class="field"><label>COGS (₦):</label><input type="text"></div><div class="field"><label>Gross Profit (₦):</label><input type="text"></div></div><div class="section"><h2>Operating Expenses</h2><table><thead><tr><th>Expense Category</th><th>Amount (₦)</th></tr></thead><tbody><tr><td>Salaries & Wages</td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Rent</td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Marketing</td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Net Profit/Loss</h2><div class="field"><label>Net Profit/Loss (₦):</label><input type="text" placeholder="0.00"></div></div>'}
    @{id='service-agreement'; title='Service Agreement Template'; desc='Client service contract template'; content='<div class="section"><h2>Parties</h2><div class="field"><label>Service Provider:</label><input type="text" placeholder="Your Company Name"></div><div class="field"><label>Client:</label><input type="text" placeholder="Client Name"></div></div><div class="section"><h2>Services</h2><div class="field"><label>Description of Services:</label><textarea rows="5" placeholder="Describe the services to be provided"></textarea></div></div><div class="section"><h2>Terms</h2><div class="field"><label>Service Period:</label><input type="text" placeholder="Start date to End date"></div><div class="field"><label>Payment Terms:</label><textarea rows="3" placeholder="Payment schedule and terms"></textarea></div></div><div class="section"><h2>Additional Terms</h2><textarea rows="6" placeholder="Additional terms and conditions"></textarea></div>'}
    @{id='nda'; title='Non-Disclosure Agreement'; desc='Confidentiality agreement template'; content='<div class="section"><h2>Parties</h2><div class="field"><label>Disclosing Party:</label><input type="text"></div><div class="field"><label>Receiving Party:</label><input type="text"></div></div><div class="section"><h2>Confidential Information</h2><div class="field"><label>Definition of Confidential Information:</label><textarea rows="4" placeholder="Define what constitutes confidential information"></textarea></div></div><div class="section"><h2>Obligations</h2><div class="field"><label>Receiving Party Obligations:</label><textarea rows="5" placeholder="List obligations of the receiving party"></textarea></div></div><div class="section"><h2>Term</h2><div class="field"><label>Agreement Duration:</label><input type="text" placeholder="e.g., 2 years from date of signing"></div></div>'}
    @{id='employment-contract'; title='Employment Contract Template'; desc='Standard employment contract'; content='<div class="section"><h2>Employee Information</h2><div class="field"><label>Employee Name:</label><input type="text"></div><div class="field"><label>Position/Title:</label><input type="text"></div><div class="field"><label>Employee ID:</label><input type="text"></div></div><div class="section"><h2>Employment Terms</h2><div class="field"><label>Start Date:</label><input type="date"></div><div class="field"><label>Employment Type:</label><select style="width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;"><option>Full-time</option><option>Part-time</option><option>Contract</option></select></div><div class="field"><label>Salary (₦):</label><input type="text" placeholder="Monthly/Annual salary"></div></div><div class="section"><h2>Duties and Responsibilities</h2><textarea rows="6" placeholder="Describe job duties and responsibilities"></textarea></div><div class="section"><h2>Terms and Conditions</h2><textarea rows="6" placeholder="Additional terms and conditions"></textarea></div>'}
    @{id='partnership-agreement'; title='Partnership Agreement Template'; desc='Business partnership agreement'; content='<div class="section"><h2>Partners</h2><div class="field"><label>Partner 1 Name:</label><input type="text"></div><div class="field"><label>Partner 2 Name:</label><input type="text"></div></div><div class="section"><h2>Partnership Details</h2><div class="field"><label>Partnership Name:</label><input type="text"></div><div class="field"><label>Partnership Type:</label><input type="text" placeholder="e.g., General Partnership, Limited Partnership"></div></div><div class="section"><h2>Capital Contributions</h2><div class="field"><label>Partner 1 Contribution (₦):</label><input type="text"></div><div class="field"><label>Partner 2 Contribution (₦):</label><input type="text"></div></div><div class="section"><h2>Profit and Loss Distribution</h2><div class="field"><label>Distribution Ratio:</label><input type="text" placeholder="e.g., 50/50, 60/40"></div></div><div class="section"><h2>Management and Decision Making</h2><textarea rows="5" placeholder="Describe management structure and decision-making process"></textarea></div>'}
    @{id='terms-of-service'; title='Terms of Service Template'; desc='Website and service terms'; content='<div class="section"><h2>Service Description</h2><div class="field"><label>Service Name:</label><input type="text" placeholder="Your service or website name"></div><div class="field"><label>Service Description:</label><textarea rows="4" placeholder="Describe your service"></textarea></div></div><div class="section"><h2>User Obligations</h2><textarea rows="5" placeholder="List user obligations and acceptable use policies"></textarea></div><div class="section"><h2>Limitation of Liability</h2><textarea rows="4" placeholder="Limitation of liability clauses"></textarea></div><div class="section"><h2>Intellectual Property</h2><textarea rows="4" placeholder="Intellectual property rights and ownership"></textarea></div><div class="section"><h2>Termination</h2><textarea rows="3" placeholder="Terms for service termination"></textarea></div>'}
    @{id='privacy-policy'; title='Privacy Policy Template'; desc='Data protection and privacy policy'; content='<div class="section"><h2>Information We Collect</h2><textarea rows="5" placeholder="Describe what information you collect from users"></textarea></div><div class="section"><h2>How We Use Information</h2><textarea rows="5" placeholder="Explain how collected information is used"></textarea></div><div class="section"><h2>Data Protection</h2><textarea rows="4" placeholder="Describe data protection measures"></textarea></div><div class="section"><h2>Third-Party Sharing</h2><textarea rows="4" placeholder="Explain if and how data is shared with third parties"></textarea></div><div class="section"><h2>User Rights</h2><textarea rows="4" placeholder="Describe user rights regarding their data"></textarea></div>'}
    @{id='job-description'; title='Job Description Template'; desc='Standardized job description'; content='<div class="section"><h2>Position Details</h2><div class="field"><label>Job Title:</label><input type="text"></div><div class="field"><label>Department:</label><input type="text"></div><div class="field"><label>Reports To:</label><input type="text"></div></div><div class="section"><h2>Job Summary</h2><textarea rows="4" placeholder="Brief summary of the position"></textarea></div><div class="section"><h2>Key Responsibilities</h2><textarea rows="8" placeholder="List main job responsibilities"></textarea></div><div class="section"><h2>Required Qualifications</h2><textarea rows="5" placeholder="Education, experience, and skills required"></textarea></div><div class="section"><h2>Compensation</h2><div class="field"><label>Salary Range (₦):</label><input type="text" placeholder="e.g., 500,000 - 800,000"></div></div>'}
    @{id='employee-handbook'; title='Employee Handbook Template'; desc='Company policies and procedures'; content='<div class="section"><h2>Welcome</h2><textarea rows="3" placeholder="Welcome message to employees"></textarea></div><div class="section"><h2>Company Mission and Values</h2><textarea rows="4" placeholder="Company mission statement and core values"></textarea></div><div class="section"><h2>Employment Policies</h2><textarea rows="6" placeholder="Employment policies including working hours, leave, etc."></textarea></div><div class="section"><h2>Code of Conduct</h2><textarea rows="5" placeholder="Expected behavior and conduct standards"></textarea></div><div class="section"><h2>Benefits and Compensation</h2><textarea rows="4" placeholder="Employee benefits and compensation structure"></textarea></div>'}
    @{id='performance-review'; title='Performance Review Template'; desc='Employee performance evaluation'; content='<div class="section"><h2>Employee Information</h2><div class="field"><label>Employee Name:</label><input type="text"></div><div class="field"><label>Review Period:</label><input type="text" placeholder="e.g., Q1 2026"></div><div class="field"><label>Reviewer Name:</label><input type="text"></div></div><div class="section"><h2>Performance Goals</h2><textarea rows="5" placeholder="List performance goals and objectives"></textarea></div><div class="section"><h2>Achievements</h2><textarea rows="5" placeholder="Key achievements during review period"></textarea></div><div class="section"><h2>Areas for Improvement</h2><textarea rows="5" placeholder="Areas that need improvement"></textarea></div><div class="section"><h2>Overall Rating</h2><div class="field"><label>Rating:</label><select style="width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;"><option>Excellent</option><option>Good</option><option>Satisfactory</option><option>Needs Improvement</option></select></div></div>'}
    @{id='leave-request'; title='Leave Request Form'; desc='Employee time-off request form'; content='<div class="section"><h2>Employee Information</h2><div class="field"><label>Employee Name:</label><input type="text"></div><div class="field"><label>Employee ID:</label><input type="text"></div><div class="field"><label>Department:</label><input type="text"></div></div><div class="section"><h2>Leave Details</h2><div class="field"><label>Leave Type:</label><select style="width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;"><option>Annual Leave</option><option>Sick Leave</option><option>Personal Leave</option><option>Maternity/Paternity Leave</option></select></div><div class="field"><label>Start Date:</label><input type="date"></div><div class="field"><label>End Date:</label><input type="date"></div><div class="field"><label>Number of Days:</label><input type="number"></div></div><div class="section"><h2>Reason</h2><textarea rows="4" placeholder="Reason for leave request"></textarea></div>'}
    @{id='timesheet'; title='Timesheet Template'; desc='Hourly employee time tracking'; content='<div class="section"><h2>Employee Information</h2><div class="field"><label>Employee Name:</label><input type="text"></div><div class="field"><label>Week Ending:</label><input type="date"></div></div><div class="section"><h2>Time Entries</h2><table><thead><tr><th>Date</th><th>Project/Task</th><th>Hours</th></tr></thead><tbody><tr><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td></tr><tr><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td></tr><tr><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Total Hours</h2><div class="field"><label>Total Hours Worked:</label><input type="text" placeholder="0"></div></div>'}
    @{id='customer-onboarding'; title='Customer Onboarding Checklist'; desc='New client setup checklist'; content='<div class="section"><h2>Customer Information</h2><div class="field"><label>Customer Name:</label><input type="text"></div><div class="field"><label>Contact Email:</label><input type="email"></div><div class="field"><label>Contact Phone:</label><input type="tel"></div></div><div class="section"><h2>Onboarding Checklist</h2><table><thead><tr><th>Task</th><th>Status</th><th>Date Completed</th><th>Notes</th></tr></thead><tbody><tr><td>Account Setup</td><td><input type="checkbox"></td><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Contract Signed</td><td><input type="checkbox"></td><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Payment Setup</td><td><input type="checkbox"></td><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr><tr><td>Initial Training</td><td><input type="checkbox"></td><td><input type="date" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div>'}
    @{id='sales-proposal'; title='Sales Proposal Template'; desc='Professional sales proposal'; content='<div class="section"><h2>Proposal Details</h2><div class="field"><label>Proposal Date:</label><input type="date"></div><div class="field"><label>Valid Until:</label><input type="date"></div></div><div class="section"><h2>Client Information</h2><div class="field"><label>Client Name:</label><input type="text"></div><div class="field"><label>Client Company:</label><input type="text"></div></div><div class="section"><h2>Proposed Solution</h2><textarea rows="6" placeholder="Describe the proposed solution or service"></textarea></div><div class="section"><h2>Pricing</h2><table><thead><tr><th>Item/Service</th><th>Quantity</th><th>Unit Price (₦)</th><th>Total (₦)</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Terms and Conditions</h2><textarea rows="4" placeholder="Payment terms and project timeline"></textarea></div>'}
    @{id='customer-feedback'; title='Customer Feedback Form'; desc='Customer satisfaction survey'; content='<div class="section"><h2>Customer Information</h2><div class="field"><label>Customer Name:</label><input type="text"></div><div class="field"><label>Email:</label><input type="email"></div><div class="field"><label>Date:</label><input type="date"></div></div><div class="section"><h2>Service Rating</h2><div class="field"><label>Overall Satisfaction:</label><select style="width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;"><option>Excellent</option><option>Good</option><option>Average</option><option>Poor</option></select></div><div class="field"><label>Would you recommend us?</label><select style="width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;"><option>Yes</option><option>No</option><option>Maybe</option></select></div></div><div class="section"><h2>Feedback</h2><div class="field"><label>What did you like most?</label><textarea rows="3"></textarea></div><div class="field"><label>What can we improve?</label><textarea rows="3"></textarea></div><div class="field"><label>Additional Comments:</label><textarea rows="4"></textarea></div></div>'}
    @{id='refund-policy'; title='Refund/Return Policy Template'; desc='Return and refund policy'; content='<div class="section"><h2>Refund Policy</h2><div class="field"><label>Refund Eligibility Period:</label><input type="text" placeholder="e.g., 30 days from purchase"></div><div class="field"><label>Refund Conditions:</label><textarea rows="5" placeholder="Conditions under which refunds are granted"></textarea></div></div><div class="section"><h2>Return Process</h2><textarea rows="5" placeholder="Step-by-step return process"></textarea></div><div class="section"><h2>Non-Refundable Items</h2><textarea rows="4" placeholder="List items or services that are non-refundable"></textarea></div><div class="section"><h2>Contact Information</h2><div class="field"><label>Returns Email:</label><input type="email"></div><div class="field"><label>Returns Phone:</label><input type="tel"></div></div>'}
    @{id='inventory-checklist'; title='Inventory Checklist Template'; desc='Stock management checklist'; content='<div class="section"><h2>Inventory Details</h2><div class="field"><label>Inventory Date:</label><input type="date"></div><div class="field"><label>Location/Warehouse:</label><input type="text"></div></div><div class="section"><h2>Inventory Items</h2><table><thead><tr><th>Item Name</th><th>SKU/Code</th><th>Expected Qty</th><th>Actual Qty</th><th>Variance</th><th>Notes</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="number" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div>'}
    @{id='vendor-agreement'; title='Vendor/Supplier Agreement Template'; desc='Supplier contract template'; content='<div class="section"><h2>Parties</h2><div class="field"><label>Buyer/Company:</label><input type="text"></div><div class="field"><label>Vendor/Supplier:</label><input type="text"></div></div><div class="section"><h2>Products/Services</h2><textarea rows="4" placeholder="Description of products or services to be supplied"></textarea></div><div class="section"><h2>Terms</h2><div class="field"><label>Payment Terms:</label><textarea rows="3" placeholder="Payment schedule and terms"></textarea></div><div class="field"><label>Delivery Terms:</label><textarea rows="3" placeholder="Delivery schedule and terms"></textarea></div></div><div class="section"><h2>Pricing</h2><div class="field"><label>Pricing Structure:</label><textarea rows="3" placeholder="Pricing details"></textarea></div></div>'}
    @{id='meeting-agenda'; title='Meeting Agenda Template'; desc='Structured meeting agenda'; content='<div class="section"><h2>Meeting Information</h2><div class="field"><label>Meeting Title:</label><input type="text"></div><div class="field"><label>Date:</label><input type="date"></div><div class="field"><label>Time:</label><input type="time"></div><div class="field"><label>Location:</label><input type="text"></div></div><div class="section"><h2>Attendees</h2><textarea rows="3" placeholder="List meeting attendees"></textarea></div><div class="section"><h2>Agenda Items</h2><table><thead><tr><th>Time</th><th>Topic</th><th>Presenter</th><th>Notes</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td></tr></tbody></table></div><div class="section"><h2>Action Items</h2><textarea rows="4" placeholder="Action items and follow-ups"></textarea></div>'}
    @{id='project-plan'; title='Project Plan Template'; desc='Project management framework'; content='<div class="section"><h2>Project Information</h2><div class="field"><label>Project Name:</label><input type="text"></div><div class="field"><label>Project Manager:</label><input type="text"></div><div class="field"><label>Start Date:</label><input type="date"></div><div class="field"><label>End Date:</label><input type="date"></div></div><div class="section"><h2>Project Objectives</h2><textarea rows="4" placeholder="Project goals and objectives"></textarea></div><div class="section"><h2>Project Scope</h2><textarea rows="4" placeholder="What is included and excluded from the project"></textarea></div><div class="section"><h2>Timeline and Milestones</h2><table><thead><tr><th>Milestone</th><th>Target Date</th><th>Status</th></tr></thead><tbody><tr><td><input type="text" style="width:100%;border:none;"></td><td><input type="date" style="width:100%;border:none;"></td><td><select style="width:100%;border:none;"><option>Not Started</option><option>In Progress</option><option>Completed</option></select></td></tr></tbody></table></div><div class="section"><h2>Budget</h2><div class="field"><label>Project Budget (₦):</label><input type="text"></div></div>'}
    @{id='social-media-calendar'; title='Social Media Content Calendar'; desc='Monthly social media scheduling'; content='<div class="section"><h2>Calendar Period</h2><div class="field"><label>Month/Year:</label><input type="text" placeholder="e.g., January 2026"></div></div><div class="section"><h2>Content Schedule</h2><table><thead><tr><th>Date</th><th>Platform</th><th>Content Type</th><th>Content Description</th><th>Status</th></tr></thead><tbody><tr><td><input type="date" style="width:100%;border:none;"></td><td><select style="width:100%;border:none;"><option>Facebook</option><option>Instagram</option><option>Twitter</option><option>LinkedIn</option></select></td><td><input type="text" style="width:100%;border:none;"></td><td><input type="text" style="width:100%;border:none;"></td><td><select style="width:100%;border:none;"><option>Scheduled</option><option>Published</option><option>Draft</option></select></td></tr></tbody></table></div>'}
    @{id='press-release'; title='Press Release Template'; desc='Professional press release'; content='<div class="section"><h2>Press Release Header</h2><div class="field"><label>FOR IMMEDIATE RELEASE</label></div><div class="field"><label>Headline:</label><input type="text" style="font-size:1.2em;font-weight:bold;"></div><div class="field"><label>Subheadline:</label><input type="text"></div></div><div class="section"><h2>Contact Information</h2><div class="field"><label>Contact Name:</label><input type="text"></div><div class="field"><label>Company:</label><input type="text"></div><div class="field"><label>Email:</label><input type="email"></div><div class="field"><label>Phone:</label><input type="tel"></div></div><div class="section"><h2>Press Release Body</h2><div class="field"><label>Location and Date:</label><input type="text" placeholder="e.g., Lagos, Nigeria - January 15, 2026"></div><div class="field"><label>Body:</label><textarea rows="10" placeholder="Write your press release content here"></textarea></div></div><div class="section"><h2>About</h2><textarea rows="4" placeholder="About section describing your company"></textarea></div>'}
    @{id='email-newsletter'; title='Email Newsletter Template'; desc='Customer newsletter template'; content='<div class="section"><h2>Newsletter Header</h2><div class="field"><label>Newsletter Title:</label><input type="text" style="font-size:1.3em;font-weight:bold;"></div><div class="field"><label>Issue Date:</label><input type="date"></div><div class="field"><label>Issue Number:</label><input type="text" placeholder="e.g., Issue #1"></div></div><div class="section"><h2>Featured Content</h2><div class="field"><label>Main Headline:</label><input type="text" style="font-size:1.1em;"></div><div class="field"><label>Featured Article:</label><textarea rows="6" placeholder="Main article content"></textarea></div></div><div class="section"><h2>Additional Sections</h2><div class="field"><label>Section 1 Title:</label><input type="text"></div><div class="field"><label>Section 1 Content:</label><textarea rows="4"></textarea></div><div class="field"><label>Section 2 Title:</label><input type="text"></div><div class="field"><label>Section 2 Content:</label><textarea rows="4"></textarea></div></div><div class="section"><h2>Call to Action</h2><div class="field"><label>CTA Text:</label><input type="text" placeholder="e.g., Visit our website, Contact us"></div></div>'}
)

foreach ($template in $templates) {
    $content = $baseTemplate -replace '{{TITLE}}', $template.title -replace '{{DESCRIPTION}}', $template.desc -replace '{{CONTENT}}', $template.content
    $filePath = Join-Path $templatesDir "$($template.id).html"
    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Host "Created: $($template.id).html"
}

Write-Host "All templates created successfully!"
